### ISSUE TITLE
How to get URL to connect for new client ?? 

### ISSUE THREAD

**Issue by F0restonn** [iwatkot/py3xui#29]
api.client.get_by_email('email') doesnt have any operator to get URL

**Comment by iwatkot** [comment]
@F0restonn, hey!

I guess you're talking about the connection string (along with the QR code)?

Here's the reference for the VLESS:

![image](https://github.com/user-attachments/assets/fd6339a1-b265-4444-8d4b-bafb86c40982)

I highlighted the most important parameters; others may vary, and also, for different protocols, they can be different. The easiest approach for your case - is to generate it from the panel and investigate.

Sincerely
