### ISSUE TITLE
3xui was updated

### ISSUE THREAD

**Issue by Mooncake911** [iwatkot/py3xui#3]
Hi! Thank u for you SDK, great job!\
Today I updated to the last [v2.3.11](https://github.com/MHSanaei/3x-ui/releases/tag/v2.3.11) 3x-ui version and faced with a problem that your SDK was incompatible.\
The reason is that [MHSanaei](https://github.com/MHSanaei) added [bash - Reset Web Base Path](https://github.com/MHSanaei/3x-ui/commit/f481ab993ed82de27405bb0cae0eafa9f54c5bea) in version [v2.3.7](https://github.com/MHSanaei/3x-ui/releases/tag/v2.3.7)\
[3x-ui README](https://github.com/MHSanaei/3x-ui/blob/main/README.md):\
![image](https://github.com/user-attachments/assets/7ae8b883-10f0-4777-9387-1452dffad051)\
_P.s. also [MHSanaei](https://github.com/MHSanaei) added some new api requests and changed the previous._

**Comment by iwatkot** [comment]
@Mooncake911, hey there!

Thanks for the report!
I assumed that this would happen eventually, so I guess it's time to add a compatibility table to README.

Regarding the update, I think I will do it in a couple of weeks. But I believe that it will be a usual thing that the SDK will not be compatible with the latest versions of the software.

Sincerely

**Comment by iwatkot** [comment]
@Mooncake911 if you don't mind, I'll keep this open until the new release.

**Comment by iwatkot** [comment]
So the main issue came from changing the cookie name from `session` to `3x-ui`, which was easy to fix.
Regarding the `URI Path` option, I'll add it soon as an argument in the constructor, since it's kinda easy thing to do.

**Comment by iwatkot** [comment]
Regarding changes in the API the only one I found is a new method: https://github.com/MHSanaei/3x-ui/commit/c7906e85980c45fd3f37d11b80e14a1075d94d4f

`/getClientTrafficsById/:id`

Which I will add soon too.

**Comment by iwatkot** [comment]
@Mooncake911, so here's a summary:

1. The compatibility issue is fixed.
2. I added information about the URI Path to the README. tl;dr you can just add it to the host.
3. I added a new method to get client traffic by ID for both APIs.
4. I added a compatibility table to the README.

You can use the latest version of the SDK now:

```bash
pip install py3xui==0.2.2
```

Thanks again for the report and don't hesitate to open a new issue if you face any problems.
You are also welcome to contribute to the project.

Have a nice day
Sincerely
