### ISSUE TITLE
get_by_tg_id

### ISSUE THREAD

**Issue by Spp595** [iwatkot/py3xui#31]
it would be really cool to have a function like get_by_email but using tg_id

**Comment by iwatkot** [comment]
@Spp595, hello!

Thanks for the suggestion, but at the moment there is no such endpoint in the 3x-ui API: https://www.postman.com/hsanaei/3x-ui/overview

We can get the Client by ID or by email, so even if we create a wrapper to get the Client by tg_id, we still need to use one of those parameters under the hood, which does not sound like a convenient and/or straightforward way to achieve the goal.

Sincerely
