### ISSUE TITLE
change existing user

### ISSUE THREAD

**Issue by Spp595** [iwatkot/py3xui#37]
how can i change the expiration time of a link for an existing user?

**Comment by iwatkot** [comment]
@Spp595, hello!

Please clarify what is the "link" of a user?
Provide a screenshot of the feature in 3x-ui panel and it would be nice if you check the source API docs and point out on the exact parameter you need.

Sincerely

**Comment by Spp595** [comment]
I'm talking about expiry_time, I already found how)))

**Comment by Spp595** [comment]
I found the function, but it does not work correctly, when I use api.client.update(client.id, client) it replaces the client value with those that I specified in the client class object, but is it possible to somehow add, change only one value without changing all?

**Comment by Spp595** [comment]
exemple:
```
    api = Api.from_env()
    api.login()
    client = api.client.get_by_email(email)
    client.id = get_user_uuid(uuid)
    client.expiry_time = int(new_dt.timestamp() * 1000)
    api.client.update(client.id, client)
```
when I run this code the user's tg_id and flow are deleted

**Comment by iwatkot** [comment]
@Spp595, please provide the all required information, which the bot suggested in the first comment.

‼️ Especially the payload of the request to the 3x-ui panel API.

Ensure that the payload has the required fields and they have the correct values. If they exist, and have correct values - then please report it as stated above.

Thank you
Sincerely

**Comment by iwatkot** [comment]
Closed as stale.
