### ISSUE TITLE
get_traffic_by_id

### ISSUE THREAD

**Issue by ap1w1** [iwatkot/py3xui#44]
How do I find out how much traffic the client has consumed?

`await async_api.client.get_traffic_by_id(client_uuid="...")` -> **Returns {..., up=0, donw=0}**. But the control panel has a different value

**Comment by iwatkot** [comment]
@ap1w1 in addition to the list above please share the JSON response from the API.

Thank you

**Comment by ap1w1** [comment]
I'm sorry, the problem is different, I'm calling `await async_api.inbound.get_by_id(inbound_id=inbound_id)`, and if the connection is exhausted, then `down=0`, also does not indicate that it is disabled.

`Client(email='208-6363077166', enable=True, id='d50ab069-13e1-4826-b1c9-1fb27a59e541', password='', inbound_id=2, up=0, down=0, expiry_time=1733584790967, total=0, reset=None, flow='', method='', limit_ip=1, sub_id='', tg_id='6363077166', total_gb=0)`
![image](https://github.com/user-attachments/assets/ec5b0065-ecaa-4c8c-8f81-f765b27db08c)
![image](https://github.com/user-attachments/assets/2186d253-4d92-4bd2-aabd-8253dc28e335)

**Comment by ap1w1** [comment]
It displays traffic only from active clients, how do I get the total?

**Comment by iwatkot** [comment]
@ap1w1, if there are no values in the API response the SDK can't help it.

Just checked with a simple code snippet and the API returned the correct values.

```python
from py3xui import Api

host = "****************"
login = "****************"
password = "****************"

api = Api(host, login, password)
api.login()

uuid = "****************"

clients = api.client.get_traffic_by_id(uuid)

for client in clients:
    in_mb = client.up / 1000 / 1000
    print(f"Client used {in_mb:.2f} MB") # Client used 44745.68 MB
```

Check the payload, IDs, panel settings, and so on. Are you sure that it should be None? As far as I remember it can return a list of Clients if UUID matches in different Inbounds, so are you looking at the correct entry in response?
