### ISSUE TITLE
api.client.update

### ISSUE THREAD

**Issue by dw1sten** [iwatkot/py3xui#45]
When I try to update expiry_time, I get the error: ''`ValueError: Response status is not successful, message: Something went wrong! Failed: empty client ID`", but I tried to enter the client.id obtained via get_by_email and the client uuid as an example.
```
    await api.login()
    expiry_time = datetime.now() + timedelta(days=1)
    expiry_time = datetime.timestamp(expiry_time) * 1000
    client = await api.client.get_by_email(f'user_{tg_id}')
    client.expiry_time += int(expiry_time)
    inbounds: list[Inbound] = await api.inbound.get_list()
    inbounds = inbounds[0]
    for i in inbounds.settings.clients:
        if i.email == f'user_{tg_id}':
            client_uuid = i.id
    await api.client.update(client_uuid=client_uuid, client=client)
```

Even when I try to change the email as indicated in the example, I get the same error.

**Comment by iwatkot** [comment]
@dw1sten, hello!

Please, provide the information that bot requested, especially the payload and the address of the POST request to the API.

Regards

**Comment by dw1sten** [comment]
File "C:\Users\dansu\Desktop\vpn-bot\.venv\Lib\site-packages\py3xui\async_api\async_api_client.py", line 188, in update
    await self._post(url, headers, data)
  File "C:\Users\dansu\Desktop\vpn-bot\.venv\Lib\site-packages\py3xui\async_api\async_api_base.py", line 300, in _post
    return await self._request_with_retry(ApiFields.POST, url, headers, json=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dansu\Desktop\test\.venv\Lib\site-packages\py3xui\async_api\async_api_base.py", line 218, in _request_with_retry
    await self._check_response(response)
  File "C:\Users\dansu\Desktop\test\.venv\Lib\site-packages\py3xui\async_api\async_api_base.py", line 280, in _check_response
    raise ValueError(f"Response status is not successful, message: {message}")
ValueError: Response status is not successful, message: Something went wrong! Failed: empty client ID

**Comment by iwatkot** [comment]
@dw1sten, not the traceback.
API endpoint.
Request body (payload).

Regards

**Comment by dw1sten** [comment]
Sorry, I'm not very experienced and don't know where to look for this. Do you mean host url?

**Comment by iwatkot** [comment]
@dw1sten, the library is just a wrapper to create requests to the 3x-ui API. So each time you're doing something it makes a GET or a POST request to the API.
The actual data of your request is in the payload of the request. 
The reason, I've asked you about it, is because it's obvious that the payload is incorrect and the error describes what's wrong with it.
I guess that the reason for the error is here:
```
client_uuid = i.id
```

Because you will not get UUID there, only numeric, like 1, 2, 3, and so on.
And that's why you see the error.

But to investigate it, you need to check what you're sending to the API.

I'm closing the issue. If you check everything and will be completely sure that all the values are correct and the payload looks right, but still there's an error - you can reopen it.

Regards

**Comment by ra1nbow1** [comment]
But `.update(client.id, ...)` is provided in the [documentation](https://github.com/iwatkot/py3xui/blob/main/py3xui/api/README.md#update). It's strange that you need UUID to update the client, but there's no way to get the UUID with API

**Comment by iwatkot** [comment]
@ra1nbow1, it's from the official documentation: https://documenter.getpostman.com/view/16802678/2s9YkgD5jm#af1bee51-199c-4176-b3ab-d325ba2fae19

![image](https://github.com/user-attachments/assets/bff470b7-2f38-47e0-9f7e-efd9f1f14bbe)

If you find a way to obtain UUID and/or if some changes need to be made, just let me know.

Regards

**Comment by ra1nbow1** [comment]
> @ra1nbow1, it's from the official documentation: https://documenter.getpostman.com/view/16802678/2s9YkgD5jm#af1bee51-199c-4176-b3ab-d325ba2fae19
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/bff470b7-2f38-47e0-9f7e-efd9f1f14bbe)
> 
> 
> 
> If you find a way to obtain UUID and/or if some changes need to be made, just let me know.
> 
> 
> 
> Regards

Such a wonderful answer

**Comment by ra1nbow1** [comment]
@iwatkot so how to update the client? It doesn't work even with UUID

**Comment by iwatkot** [comment]
@ra1nbow1, there are two main reasons for an answer like this.

1. There's only one discussion in the FAQ, and it's [about this particular question](https://github.com/iwatkot/py3xui/discussions/10). And it's already contained the answer on how to obtain the actual UUIDs. Spoiler: it looks like only one specific endpoint returns them, while others return IDs as numerical values.
2. I want to once more pay attention to the fact that the SDK is not a magic app with its own server. Instead, it's a wrapper around 3x-ui API. So if the API returns ID as a numerical value, as a result, in the pydantic model, you'll have the same value, not some UUID obtained somewhere from the magic box. And SDK not only cannot, but also should not mutate API responses in any way. I hope this is clear.

It doesn't work even with UUID

This question is directly related to the point number two above, while you can find the answer from the point number one. The reason for this is quite simple: in your Client object you have numerical value and when you pass it to the API it won't work.
So either you obtain the Client object from the endpoint which returns UUIDs, or you manually set the ID property to the correct one.

Update option: https://github.com/iwatkot/py3xui/discussions/10#discussioncomment-10529998
Get option: https://github.com/iwatkot/py3xui/discussions/10#discussioncomment-11784982

Regards

**Comment by ra1nbow1** [comment]
That's so sweet of you. Very friendly response, as always
