### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by Mooncake911** [iwatkot/py3xui#5]
Hi, @iwatkot! It's me again :)\
I'm not sure, is it a mistake?! I assumed that the second request would return the same session if it wasn't expired yet.

``` python
import time
import asyncio
from py3xui import AsyncApi

from config import XUI_HOST, XUI_USERNAME, XUI_PASSWORD


ApiXUI = AsyncApi(host=XUI_HOST, username=XUI_USERNAME, password=XUI_PASSWORD)


async def command() -> None:
    await ApiXUI.login()
    print(ApiXUI.session)


if __name__ == '__main__':
    asyncio.run(command(), debug=True)
    time.sleep(2)
    asyncio.run(command(), debug=True)
```

> Executing <Task pending name='Task-1' coro=<command() running at D:\Projects\PyCharm_Projects\VPN\vpn_server\рр.py:12> cb=[_run_until_complete_cb() at D:\Languages\Python312\Lib\asyncio\base_events.py:182] created at D:\Languages\Python312\Lib\asyncio\runners.py:100> took 0.688 seconds
MTcyMjUzNTQ0MHxEWDhFQVFMX2dBQUJFQUVRQUFCMV80QUFBUVp6ZEhKcGJtY01EQUFLVEU5SFNVNWZWVk5GVWhoNExYVnBMMlJoZEdGaVlYTmxMMjF2WkdWc0xsVnpaWExfZ1FNQkFRUlZjMlZ5QWYtQ0FBRUVBUUpKWkFFRUFBRUlWWE5sY201aGJXVUJEQUFCQ0ZCaGMzTjNiM0prQVF3QUFRdE1iMmRwYmxObFkzSmxkQUVNQUFBQUlQLUNIUUVDQVF0TmIyOXVZMkZyWlRreE1RRUxWblpoWkdsdE1qQXhPU1FBfArqHhOFFySLEFYovj-tGCtKDaOGRpKMfHKSUfa2K_AG
Executing <Task pending name='Task-5' coro=<command() running at D:\Projects\PyCharm_Projects\VPN\vpn_server\рр.py:12> cb=[_run_until_complete_cb() at D:\Languages\Python312\Lib\asyncio\base_events.py:182] created at D:\Languages\Python312\Lib\asyncio\runners.py:100> took 0.703 seconds
MTcyMjUzNTQ0M3xEWDhFQVFMX2dBQUJFQUVRQUFCMV80QUFBUVp6ZEhKcGJtY01EQUFLVEU5SFNVNWZWVk5GVWhoNExYVnBMMlJoZEdGaVlYTmxMMjF2WkdWc0xsVnpaWExfZ1FNQkFRUlZjMlZ5QWYtQ0FBRUVBUUpKWkFFRUFBRUlWWE5sY201aGJXVUJEQUFCQ0ZCaGMzTjNiM0prQVF3QUFRdE1iMmRwYmxObFkzSmxkQUVNQUFBQUlQLUNIUUVDQVF0TmIyOXVZMkZyWlRreE1RRUxWblpoWkdsdE1qQXhPU1FBfFjPvdDpQf8QJEUtH1g-yTur1dXaHQL9fdXY3wijDJuB

**Comment by iwatkot** [comment]
@Mooncake911 hey!
The login() method is making a request to the /login endpoint of the API, and, as far as I know the API returns a new cookie on each request.
So it is an expected behavior.

By the way, it is expected that login() method will be called only once (or once per some amount of time). And all other methods will use the saved cookie.

**Comment by Mooncake911** [comment]
I'm sorry, I needed to check the origin 3xui API behaviour before writing you. So I've done it now, your are right!\
I'm probably accustomed to temporal session key.

**Comment by Mooncake911** [comment]
> @Mooncake911 hey! The login() method is making a request to the /login endpoint of the API, and, as far as I know the API returns a new cookie on each request. So it is an expected behavior.
> 
> By the way, it is expected that login() method will be called only once (or once per some amount of time). And all other methods will use the saved cookie.

I'm sorry, I needed to check the origin 3xui API behaviour before writing you. So I've done it now, your are right!
I'm probably accustomed to temporal session key.

**Comment by iwatkot** [comment]
@Mooncake911 it's not a big deal, don't worry about it.
By the way, Idk what you're working on, but the SDK is designed for a high-level usage, when you don't need to bother yourself with cookies and all this stuff.
Just call the login once and make all other requests without calling it each time and without manual handling of the cookie. 

Regards
